config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  get 'page/about'
  get 'page/portfolio'
  get 'page/contact'
  get 'page/cats'

  # Defines the root path route ("/")
  root "page#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/page_controller.rb
class PageController < ApplicationController

  def about 
  end
   
  def portfolio
  end
  
  def contact
  end
  
  def cats
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def device
    agent = request.user_agent
    return "tablet" if agent =~ /(tablet|ipad)|(android(?!.*mobile))/i
    return "mobile" if agent =~ /Mobile/
    return "desktop"
  end

end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar sticky-top navbar-dark navbar-expand-lg bg-dark fixed-top bg-body-tertiary" style="width: 100vw">
  <div class="container-fluid">
    <%= link_to 'David Bielik (🐝 + 👅)', root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">David Bielik (🐝 + 👅) </h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">  
            <div class="d-flex align-items-center">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
                <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5Z"/>
              </svg>
              <%= link_to "Home", root_path, class:'nav-link active', aria_current:'page', style:"margin-left: 5px; margin-right: 20px" %>
              
            </div>
          </li>
          <li class="nav-item">
            <div class="d-flex align-items-center">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-person-fill" viewBox="0 0 16 16">
                <path d="M12 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zm-1 7a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm-3 4c2.623 0 4.146.826 5 1.755V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-1.245C3.854 11.825 5.377 11 8 11z"/>
              </svg>
              <%= link_to "About Me", page_about_path, class:'nav-link active', aria_current:'page', style:"margin-left: 5px; margin-right: 20px" %>
            </div>
          </li>
          <li class="nav-item">
            <div class="d-flex align-items-center">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-briefcase-fill" viewBox="0 0 16 16">
                <path d="M6.5 1A1.5 1.5 0 0 0 5 2.5V3H1.5A1.5 1.5 0 0 0 0 4.5v1.384l7.614 2.03a1.5 1.5 0 0 0 .772 0L16 5.884V4.5A1.5 1.5 0 0 0 14.5 3H11v-.5A1.5 1.5 0 0 0 9.5 1h-3zm0 1h3a.5.5 0 0 1 .5.5V3H6v-.5a.5.5 0 0 1 .5-.5z"/>
                <path d="M0 12.5A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5V6.85L8.129 8.947a.5.5 0 0 1-.258 0L0 6.85v5.65z"/>
              </svg>
            
            <%= link_to "Portfolio", page_portfolio_path, class:'nav-link active', aria_current:'page', style:"margin-left: 5px; margin-right: 20px"%> 
            </div>
          </li>
          <li class="">
            <div class="d-flex align-items-center">

              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-square-text-fill" viewBox="0 0 16 16">
                <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.5a1 1 0 0 0-.8.4l-1.9 2.533a1 1 0 0 1-1.6 0L5.3 12.4a1 1 0 0 0-.8-.4H2a2 2 0 0 1-2-2V2zm3.5 1a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z"/>
              </svg>
              <%= link_to "Contact Me", page_contact_path, class:'nav-link active', aria_current:'page', style:"margin-left: 5px" %>
            </div>
          </li>
        </ul>
        
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>David Bielik - Data Analyst | Web Developer | Mathematician</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'layouts/header' %>
    <%= javascript_importmap_tags %>
  </head>

  <div class="bg-dark" style="min-height:100vh; min-width:100vw;">
    <body>
      <%= yield %>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
  </div>
  
</html>

app/views/page/_contact.html.erb
<div class="d-flex justify-content-center">
  <div class="card bg-dark text-bg-dark rounded-0 border-0" style="height: auto; width: 100%; max-width:30rem;">
    <div class="text-center">
      
        <% if current_page?(page_contact_path)%>
          
            <div class="card rounded-0 border-0", style="background-color: #4B878BFF;" >
              <div class="card-body">
              <h1 class="card-title" style="margin-bottom: 20px">Contact Me</h1>
             
              <div class="card bg-light mx-auto" style="--bs-bg-opacity: 0; border: none; max-width: 300px;">
                <div class="card bg-light shadow-lg" style="--bs-bg-opacity: 0.9; border: none;">
                  <div class="card-body text-dark">
                    <h5 class="card-title" style="margin-bottom: 20px">
                    Send me a message</h5>
                    
                    <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="#591c0b" class="bi bi-envelope-at" viewBox="0 0 16 16" style="margin-bottom: 10px">
                      <path d="M2 2a2 2 0 0 0-2 2v8.01A2 2 0 0 0 2 14h5.5a.5.5 0 0 0 0-1H2a1 1 0 0 1-.966-.741l5.64-3.471L8 9.583l7-4.2V8.5a.5.5 0 0 0 1 0V4a2 2 0 0 0-2-2H2Zm3.708 6.208L1 11.105V5.383l4.708 2.825ZM1 4.217V4a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v.217l-7 4.2-7-4.2Z"/>
                      <path d="M14.247 14.269c1.01 0 1.587-.857 1.587-2.025v-.21C15.834 10.43 14.64 9 12.52 9h-.035C10.42 9 9 10.36 9 12.432v.214C9 14.82 10.438 16 12.358 16h.044c.594 0 1.018-.074 1.237-.175v-.73c-.245.11-.673.18-1.18.18h-.044c-1.334 0-2.571-.788-2.571-2.655v-.157c0-1.657 1.058-2.724 2.64-2.724h.04c1.535 0 2.484 1.05 2.484 2.326v.118c0 .975-.324 1.39-.639 1.39-.232 0-.41-.148-.41-.42v-2.19h-.906v.569h-.03c-.084-.298-.368-.63-.954-.63-.778 0-1.259.555-1.259 1.4v.528c0 .892.49 1.434 1.26 1.434.471 0 .896-.227 1.014-.643h.043c.118.42.617.648 1.12.648Zm-2.453-1.588v-.227c0-.546.227-.791.573-.791.297 0 .572.192.572.708v.367c0 .573-.253.744-.564.744-.354 0-.581-.215-.581-.8Z"/>
                    </svg>
                    <p class="card-text d-flex justify-content-center">
            
                      davidbielik@gmail.com</p>
                      
                      <a href="mailto: davidbielik@gmail.com" class="btn btn-secondary shadow-sm" style="text-decoration: none; border-radius: 20px;">Email me</a>
                        
                      
                  </div>
                  <div class="card-body text-dark">
                    
                    <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="currentColor" class="bi bi-chat-left-text" viewBox="0 0 16 16" style="margin-bottom: 10px">
                      <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4.414A2 2 0 0 0 3 11.586l-2 2V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12.793a.5.5 0 0 0 .854.353l2.853-2.853A1 1 0 0 1 4.414 12H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                      <path d="M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6zm0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
                    </svg>
                    <p class="card-text d-flex justify-content-center align-items-center" style="text-decoration: none; ">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone" viewBox="0 0 16 16" style="margin-right: 5px">
                        <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
                      </svg>
                      (978) 743-9253 </p>
                    
                      <a href="sms:+19787439253" class="btn btn-secondary shadow-sm" style="text-decoration: none; border-radius: 20px; margin-bottom: 10px;">Text me</a>
                        
                  </div>
                  
                </div>
                
                <br>
                
                <div class="card bg-light shadow-lg" style="--bs-bg-opacity: 0.9; border: none;">
                  <div class="card-body text-dark ">
                    <h5 class="card-title" style="margin-bottom: 10px">Follow me</h5>
                      <div class="d-flex justify-content-around" style="margin: 20px">
                        <div>
                          <a href="https://www.linkedin.com/in/david-bielik-385186256/">
                            <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="#0077b5" viewBox="0 0 24 24"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/></svg>
                          </a>
                        </div>
                        <div>  
                          <a href="https://github.com/dbielik236">
                            <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
                          </a>
                        </div>
                        <div>  
                          <a href="https://twitter.com/davidbielik3000">
                            
                            <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="#1DA1F2"viewBox="0 0 24 24"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-.139 9.237c.209 4.617-3.234 9.765-9.33 9.765-1.854 0-3.579-.543-5.032-1.475 1.742.205 3.48-.278 4.86-1.359-1.437-.027-2.649-.976-3.066-2.28.515.098 1.021.069 1.482-.056-1.579-.317-2.668-1.739-2.633-3.26.442.246.949.394 1.486.411-1.461-.977-1.875-2.907-1.016-4.383 1.619 1.986 4.038 3.293 6.766 3.43-.479-2.053 1.08-4.03 3.199-4.03.943 0 1.797.398 2.395 1.037.748-.147 1.451-.42 2.086-.796-.246.767-.766 1.41-1.443 1.816.664-.08 1.297-.256 1.885-.517-.439.656-.996 1.234-1.639 1.697z"/></svg>
                          </a>
                        </div>
                      </div>
                  </div>
                </div>

              </div>  


              
                
              
              <br>
            </div>
          </div>
          
        <% else %>
          

          <div class="card rounded-0 border-0 mx-auto", style="background-color: #4B878BFF; height: 12rem; width: 100%; max-width:30rem;"  >
            <div class="card-body mx-auto d-flex align-items-center" style="padding-top: 0">
              <div style="max-width: 300px;">
                <h1 class="card-title">Contact Me</h1>
                 <p class="card-text">Send me a text or email or reach out through Linkedin</p>
                <%= button_to "Get in touch", page_contact_path, method: :get, class:'btn btn-light shadow-lg', style:'border-radius: 20px;' %>
              </div>
            </div>
          </div>
        <% end %>

        
        

      
    </div>  
  </div>
</div>

app/views/page/_links.html.erb
<div class="d-flex justify-content-center">
  <div class="card text-bg-dark rounded-0 border-0" style="height: 17rem; width: 100%; max-width:30rem;">
    <div class="text-center">
      
        
        <% if current_page?(page_about_path) || current_page?(page_cats_path)%>
          <div class="card rounded-0 border-0", style="background-color: #4B878BFF; height: 17rem; width: 100%; max-width:30rem;"  >
            <div class="card-body d-flex align-items-center justify-content-center flex-column">
               
                <h1 class="card-title">Contact Me</h1>
                <%= link_to "Get in touch", page_contact_path, method: :get, class:'btn btn-light shadow-lg', style:"border-radius: 20px; margin-bottom: 20px;" %>

                <h1 class="card-title">Portfolio</h1>
                <%= link_to "View my work", page_portfolio_path, method: :get, class:'btn btn-light shadow-lg', style:"border-radius: 20px; margin-bottom: 20px;" %>
              
            </div> 
          </div>
          

        <% elsif current_page?(page_contact_path) %>
          <div class="card rounded-0 border-0", style="background-color: #5B84B1FF; height: 17rem; width: 100%; max-width:30rem;"  >
            <div class="card-body d-flex align-items-center justify-content-center flex-column">
              
              <h1 class="card-title">About Me</h1>
              <%= link_to "Learn who I am", page_about_path, method: :get, class:'btn btn-light shadow-lg', style:"border-radius: 20px; margin-bottom: 20px;" %>
              
              <h1 class="card-title">Portfolio</h1>
              <%= link_to "View my work", page_portfolio_path, method: :get, class:'btn btn-light shadow-lg', style:"border-radius: 20px; margin-bottom: 20px;" %>
            
            </div> 
          </div>

        <% elsif current_page?(page_portfolio_path) %>
          <div class="card rounded-0 border-0", style="background-color: #5B84B1FF; height: 17rem; width: 100%; max-width:30rem;"  >
            <div class="card-body d-flex align-items-center justify-content-center flex-column">
              
              <h1 class="card-title">About Me</h1>
              <%= link_to "Learn who I am", page_about_path, method: :get, class:'btn btn-light shadow-lg', style:"border-radius: 20px; margin-bottom: 20px;" %>
            
              <h1 class="card-title">Contact Me</h1>
              <%= link_to "Get in touch", page_contact_path, method: :get, class:'btn btn-light shadow-lg', style:"border-radius: 20px; margin-bottom: 20px;" %>
            
            </div> 
          </div>
        <% end %>  
    </div>
  </div>
</div>

app/views/page/_portfolio.html.erb
<div class="d-flex justify-content-center">
  <div class="card text-bg-dark rounded-0 border-0" style="height: auto; width: 100%; max-width: 30rem;">
    <div class="text-center">
      
        <% if current_page?(page_portfolio_path)%>
          <div class="card rounded-0 border-0", style="background-color: #9F6B99FF;"  >
            <div class="card-body">
              <h1 class="card-title">Portfolio</h1>
              <div class="mx-auto", style="max-width: 290px;">
                <p class="card-text" style="text-align: justify; text-justify: inter-word;">
                As a Web Developer and Data Analyst I enjoy building scalable applications as well as analyzing data and creating meaningful visualizations. 
                Here are some projects that I'm particularly proud of!</p>
              
              <div class="card bg-light mx-auto" style="--bs-bg-opacity: 0; border: none; max-width: 300px;">
                </div>
                  <br>
  
                  <div class="card bg-light shadow-lg" style="--bs-bg-opacity: 0.9; border: none;">
                    <div class="card-body text-dark">
                       <h5 class="card-title">NYC Tree Census:<br>Data Analysis</h5>
                      <p class="card-text">Data analysis and visualizations with Python, Pandas, and Jupyter Notebook</p>
                      <%= image_tag 'data.png', style: 'height:auto; width:100%; max-width:50rem;' %>
                      <br>
                      <br>
                      <a href="https://github.com/dbielik236/data_exploration" class="btn btn-secondary" style="border-radius: 20px; margin-right: 5px">Code</a> 
                      <a href="https://github.com/dbielik236/data_exploration/blob/main/tree_census.ipynb" class="btn btn-secondary" style="border-radius: 20px; margin-left: 5px">Preview</a>
                    </div>
                  </div>

                  <br>
                
                  <div class="card bg-light shadow-lg" style="--bs-bg-opacity: 0.9; border: none;">
                    <div class="card-body text-dark">
                      <h5 class="card-title">Beatle-bot:<br>Machine Learning</h5>
                      <p class="card-text">An NLP built with the NLTK library in Python. It knows all things Beatles!</p>
                      <%= image_tag 'BeatleBot.gif', style: 'height:auto; width:100%; max-width:50rem;' %>
                      <br>
                      <br>
                      <a href="https://github.com/dbielik236/chat_bot" class="btn btn-secondary" style="border-radius: 20px; margin-right: 5px">Code</a> 
                      <a href="https://replit.com/@dbielik236/ChatBot" class="btn btn-secondary" style="border-radius: 20px; margin-left: 5px">Preview</a>
                    </div>
                  </div>
                <br>
                  <div class="card bg-light shadow-lg" style="--bs-bg-opacity: 0.9; border: none;">
                    <div class="card-body text-dark">
                      <h5 class="card-title">"Fakebook"<br>Web Application</h5>
                      <p class="card-text">An application replicating Facebook's capabilities with relational databases, user authentication with Devise, and responsive design with Bootstrap<br>
                      (Use Email: <code>guest@gmail.com</code> and Password: <code>password</code> for premade account)</p>
                      <%= image_tag 'fakebook.gif', class:'border border-muted', style: 'height:auto; width:100%; max-width:50rem;' %>
                      <br>
                      <br>
                      <a href="https://github.com/dbielik236/fakebook" class="btn btn-secondary" style="border-radius: 20px; margin-right: 5px">Code</a> 
                      <a href="https://blooming-temple-89582.herokuapp.com/users/sign_in" class="btn btn-secondary" style="border-radius: 20px; margin-left: 5px">Preview</a>
                    </div>
                  </div>
                
                  <br>
    
                  <div class="card bg-light shadow-lg" style="--bs-bg-opacity: 0.9; border: none;">
                    <div class="card-body text-dark">
                      <h5 class="card-title">Calculator:<br>Graphical User Interface</h5>
                      <p class="card-text">Four-function calculator made with HTML, CSS Grid, and Javascript utilizing DOM manipulation</p>
                      <%= image_tag 'calculator.png', style: 'height:auto; width:50%; border-radius: 5px' %>
                      <br>
                      <br>
                      <a href="https://github.com/dbielik236/calculator" class="btn btn-secondary" style="border-radius: 20px; margin-right: 5px">Code</a> 
                      <a href="https://dbielik236.github.io/calculator/" class="btn btn-secondary" style="border-radius: 20px; margin-left: 5px">Preview</a>
                    </div>
                  </div>
                
                <br>
                <div class="card bg-light shadow-lg mx-auto" style="--bs-bg-opacity: 0; border: none; max-width: 300px;">
                  <div class="card bg-light" style="--bs-bg-opacity: 0.9; border: none;">  
                    <div class="card-body text-dark" style="margin-bottom: 10px">
                      <h5 class="card-title" style="margin-bottom: 20px"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="margin-right: 10px" ><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
                      See more projects</h5>
                      <a href="https://github.com/dbielik236" class="btn btn-secondary" style="border-radius: 20px">View my GitHub profile</a>
                    </div>
                  </div>  
                </div>
              </div>
              <br>
            </div>
          </div>
          
        <% else %>
          <div class="card rounded-0 border-0 mx-auto", style="background-color: #9F6B99FF; height: 12rem; width: 100%; max-width:30rem;"  >
            <div class="card-body mx-auto d-flex align-items-center" style="padding-top: 0">
              <div style="max-width: 300px;">
                <h1 class="card-title">Portfolio</h1>
                <p class="card-text">Take a look at some of my projects and deployed applications</p>  
                <%= button_to "View my work", page_portfolio_path, method: :get, class:'btn btn-light shadow-lg', style:"border-radius: 20px;" %>
              </div>
            </div>
          </div>
        <% end %>
    </div>  
  </div>
</div>  

app/views/page/about.html.erb
<%= render 'about' %>

<%= render 'links'%>

app/views/page/contact.html.erb
<%= render 'contact'%>
  
<%= render 'links'%>

app/views/page/index.html.erb
<div class="text-center">
  <%= image_tag 'adalaide.jpg', alt: "David with sleeping cat in his arms", style: 'height: auto; width:100%; max-width: 30rem;'%>
</div>

<%= render 'about' %>
<%= render 'portfolio' %>
<%= render 'contact' %>

app/views/page/portfolio.html.erb
<%= render 'portfolio'%>

<%= render 'links'%>